[package]
name = "yamlvd"
version = "0.5.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
lvd_lib = { path = "../lvd_lib", features = ["serde"] }
serde_yaml = { version = "0.9" }
