---
name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - dev
          - release
    steps:
      - uses: actions/checkout@v4
      - name: cargo-check
        run: cargo check --profile ${{matrix.profile}}
      - name: cargo-test
        run: cargo test --lib --profile ${{matrix.profile}}
      - name: cargo-doc
        run: cargo doc --no-deps --lib --profile ${{matrix.profile}}
      - name: cargo-clippy
        run: cargo clippy --no-deps
      - name: cargo-fmt
        run: cargo fmt --check
